// <auto-generated>
/*
 * merged spec
 *
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using PowerOfficeGoV2.Client;

namespace PowerOfficeGoV2.Model
{
    /// <summary>
    /// Represents a supplier ledger entry.
    /// </summary>
    public partial class SupplierLedgerEntryDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SupplierLedgerEntryDto" /> class.
        /// </summary>
        /// <param name="amount">The posted amount of the entry. Amount is always presented in the client currency.  Always present on transactions.</param>
        /// <param name="balance">The balance of the entry (remaining amount to be paid), in the client currency on the date (openItems) / toDate (statement).  If balance is less than amount, the entry will have a match with at least one other entry with the opposite amount, and those entries will share the same matchId.</param>
        /// <param name="cid">The cid number (norwegian: KID), if present.  Entries with the opposite amounts and the same cid will be matched on the sub-ledger account, if the client use cid and the items are not already matched out.</param>
        /// <param name="createdDateTimeOffset">The created timestamp.  This is the timestamp the transaction was created, and may differ from the timestamp of accounting effect for the transaction (ie the property PostingDate).  Always present on transactions.</param>
        /// <param name="createdFromImportJournalId">The created from import journal identifier, if present.  Provided if this account transaction has been created in Go by an import.</param>
        /// <param name="currencyAmount">The currency amount. Differs from Amount if the transaction was posted with a currency other than the client currency.</param>
        /// <param name="currencyCode">The currency code. Currencies active on the client can be queried using the AccountingSettings service. Currency codes follow the ISO4217 standard.</param>
        /// <param name="customMatchingReference">The custom matching reference set on the transaction. This property will only have value on entries created through the API or Import with CustomMatchingReference specified.  This property is used for matching purposes, where entries posted with a CustomMatchingReference will be matched immediately with existing entries in the sub-ledger that have the same CustomMatchingReference and opposite amount (unless existing entries are already matched out).</param>
        /// <param name="departmentCode">The department code. Available if the transaction was posted with department.  Departments can be queried and identified using the Department service.</param>
        /// <param name="departmentId">The department id. Available if the transaction was posted with department.  Departments can be queried and identified using the Department service.</param>
        /// <param name="dim1Code">The code of the dimension 1 associated with the entry.  Dimension 1-3 are customizable dimensions that can be defined and queried using the CustomDimension- and CustomDimensionValue-services.</param>
        /// <param name="dim1Id">The id of the dimension 1 associated with the account transaction.</param>
        /// <param name="dim2Code">The code of the dimension 2 associated with the account transaction.  Dimension 1-3 are customizable dimensions that can be defined and queried using the CustomDimension- and CustomDimensionValue-services.</param>
        /// <param name="dim2Id">The id of the dimension 2 associated with the account transaction.</param>
        /// <param name="dim3Code">The code of the dimension 3 associated with the account transaction.  Dimension 1-3 are customizable dimensions that can be defined and queried using the CustomDimension- and CustomDimensionValue-services.</param>
        /// <param name="dim3Id">The id of the dimension 3 associated with the account transaction.</param>
        /// <param name="dueDate">The due date of the entry. Relevant only for voucher types IncomingInvoice and IncomingCreditNote. The date represent when the amount is due to be paid to the supplier.</param>
        /// <param name="externalImportReference">The ExternalImportReference, if set.  This property can be set by integrations posting vouchers in Go, in order to reference the external system and ensure a duplicate check when posting the voucher to Go (only one instance of the reference can exist).  Can be used to correlate/duplicate check transaction.</param>
        /// <param name="id">A value that uniquely identifies this (ledger) entry. The Id is assigned by Go when the transactions is posted in Go.  Always present on transactions.</param>
        /// <param name="invoiceNo">The invoice number, if the entry is an entry with the voucher type IncomingInvoice or IncomingCreditNote.  Be aware that the invoiceNo is a string, so it&#39;s not necessarily a number.</param>
        /// <param name="isCreatedByCurrentIntegration">A value indicating whether this ledger entry is created by the integration currently communicating with the API.  Will be true for all entries that are created by the same integration user (same Application Key) as the integration currently authorized.  Can be used in filtering if only the current integration&#39;s entries are relevant to report (in simplified queries of payment status of invoices, for instance).</param>
        /// <param name="isWriteOff">A value indicating whether this entry was created by the write off functionality in Go.  Such entries are not payments, but an accounting routine writing off an open item.</param>
        /// <param name="lastChangedDateTimeOffset">The timestamp of the last change of this entry.  The accounting entry in itself cannot change, but the match state of the sub-ledger entry might change.  Using last changed filtering is one way of retrieving new matched items and as such the payment status of invoices.</param>
        /// <param name="locationCode">The code of the location dimension associated with the entry, if set.</param>
        /// <param name="locationId">The id of the location dimension associated with the entry, if location code is set.</param>
        /// <param name="matchId">The match identifier on the entry, if it is matched with one or more other entries. All sub-ledger entries that are matched together share the same matchId.</param>
        /// <param name="postingDate">The posting date.  This is the date of effect in the accounting system for the Amount and CurrencyAmount (also the currency conversion date used by Go if the currency rate was not set explicit when posted).  Always present on transactions.</param>
        /// <param name="projectCode">The project code. Available if the transaction was posted with project.  Projects can be queried and identified using the Project service.</param>
        /// <param name="projectId">The project id. Available if the transaction was posted with project.  Projects can be queried and identified using the Project service.</param>
        /// <param name="supplierAccountNo">The supplier account number this sub-ledger entry is posted on.  SupplierAccountNo will also represent the Supplier number.  Suppliers can be queried and identified using the Supplier service.</param>
        /// <param name="supplierExternalNo">The external number of the supplier of this sub-ledger entry.  An external number set on the supplier is often used to reference the supplier number in the external system, if the supplier numbers are not kept in 1:1 sync between Go and the external system.  The field is available in the GUI with the name External Code.  Suppliers can be queried and identified using the Supplier service.</param>
        /// <param name="supplierId">The id of the supplier of this sub-ledger entry.  Suppliers can be queried and identified using the Supplier service.</param>
        /// <param name="supplierName">The name of the supplier of this sub-ledger entry.  Suppliers can be queried and identified using the Supplier service.</param>
        /// <param name="voucherDate">The date of the voucher.  This represents the date of the voucher, the document date of an invoice for instance,  and may differ from the transaction dates for the voucher.  Always present on transactions.</param>
        /// <param name="voucherId">The voucher identifier.  The Id is assigned by Go when the voucher is created, and is shared by all transactions within the same voucher.  Always present on transactions.</param>
        /// <param name="voucherNo">The voucher number.  This is the voucher number assigned by Go when the voucher was posted.  Voucher numbers are assigned by Go in sequence.  Always present on transactions.</param>
        /// <param name="voucherType">voucherType</param>
        [JsonConstructor]
        public SupplierLedgerEntryDto(Option<double?> amount = default, Option<double?> balance = default, Option<string?> cid = default, Option<DateTimeOffset?> createdDateTimeOffset = default, Option<Guid?> createdFromImportJournalId = default, Option<double?> currencyAmount = default, Option<string?> currencyCode = default, Option<string?> customMatchingReference = default, Option<string?> departmentCode = default, Option<long?> departmentId = default, Option<string?> dim1Code = default, Option<long?> dim1Id = default, Option<string?> dim2Code = default, Option<long?> dim2Id = default, Option<string?> dim3Code = default, Option<long?> dim3Id = default, Option<DateTimeOffset?> dueDate = default, Option<string?> externalImportReference = default, Option<long?> id = default, Option<string?> invoiceNo = default, Option<bool?> isCreatedByCurrentIntegration = default, Option<bool?> isWriteOff = default, Option<DateTimeOffset?> lastChangedDateTimeOffset = default, Option<string?> locationCode = default, Option<long?> locationId = default, Option<long?> matchId = default, Option<DateTimeOffset?> postingDate = default, Option<string?> projectCode = default, Option<long?> projectId = default, Option<long?> supplierAccountNo = default, Option<long?> supplierExternalNo = default, Option<long?> supplierId = default, Option<string?> supplierName = default, Option<DateTimeOffset?> voucherDate = default, Option<Guid?> voucherId = default, Option<long?> voucherNo = default, Option<VoucherType?> voucherType = default)
        {
            AmountOption = amount;
            BalanceOption = balance;
            CidOption = cid;
            CreatedDateTimeOffsetOption = createdDateTimeOffset;
            CreatedFromImportJournalIdOption = createdFromImportJournalId;
            CurrencyAmountOption = currencyAmount;
            CurrencyCodeOption = currencyCode;
            CustomMatchingReferenceOption = customMatchingReference;
            DepartmentCodeOption = departmentCode;
            DepartmentIdOption = departmentId;
            Dim1CodeOption = dim1Code;
            Dim1IdOption = dim1Id;
            Dim2CodeOption = dim2Code;
            Dim2IdOption = dim2Id;
            Dim3CodeOption = dim3Code;
            Dim3IdOption = dim3Id;
            DueDateOption = dueDate;
            ExternalImportReferenceOption = externalImportReference;
            IdOption = id;
            InvoiceNoOption = invoiceNo;
            IsCreatedByCurrentIntegrationOption = isCreatedByCurrentIntegration;
            IsWriteOffOption = isWriteOff;
            LastChangedDateTimeOffsetOption = lastChangedDateTimeOffset;
            LocationCodeOption = locationCode;
            LocationIdOption = locationId;
            MatchIdOption = matchId;
            PostingDateOption = postingDate;
            ProjectCodeOption = projectCode;
            ProjectIdOption = projectId;
            SupplierAccountNoOption = supplierAccountNo;
            SupplierExternalNoOption = supplierExternalNo;
            SupplierIdOption = supplierId;
            SupplierNameOption = supplierName;
            VoucherDateOption = voucherDate;
            VoucherIdOption = voucherId;
            VoucherNoOption = voucherNo;
            VoucherTypeOption = voucherType;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of VoucherType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<VoucherType?> VoucherTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets VoucherType
        /// </summary>
        [JsonPropertyName("VoucherType")]
        public VoucherType? VoucherType { get { return this.VoucherTypeOption; } set { this.VoucherTypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Amount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> AmountOption { get; }

        /// <summary>
        /// The posted amount of the entry. Amount is always presented in the client currency.  Always present on transactions.
        /// </summary>
        /// <value>The posted amount of the entry. Amount is always presented in the client currency.  Always present on transactions.</value>
        /* <example>99</example> */
        [JsonPropertyName("Amount")]
        public double? Amount { get { return this.AmountOption; } }

        /// <summary>
        /// Used to track the state of Balance
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> BalanceOption { get; }

        /// <summary>
        /// The balance of the entry (remaining amount to be paid), in the client currency on the date (openItems) / toDate (statement).  If balance is less than amount, the entry will have a match with at least one other entry with the opposite amount, and those entries will share the same matchId.
        /// </summary>
        /// <value>The balance of the entry (remaining amount to be paid), in the client currency on the date (openItems) / toDate (statement).  If balance is less than amount, the entry will have a match with at least one other entry with the opposite amount, and those entries will share the same matchId.</value>
        /* <example>502.25</example> */
        [JsonPropertyName("Balance")]
        public double? Balance { get { return this.BalanceOption; } }

        /// <summary>
        /// Used to track the state of Cid
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CidOption { get; }

        /// <summary>
        /// The cid number (norwegian: KID), if present.  Entries with the opposite amounts and the same cid will be matched on the sub-ledger account, if the client use cid and the items are not already matched out.
        /// </summary>
        /// <value>The cid number (norwegian: KID), if present.  Entries with the opposite amounts and the same cid will be matched on the sub-ledger account, if the client use cid and the items are not already matched out.</value>
        /* <example>9235400011927001</example> */
        [JsonPropertyName("Cid")]
        public string? Cid { get { return this.CidOption; } }

        /// <summary>
        /// Used to track the state of CreatedDateTimeOffset
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTimeOffset?> CreatedDateTimeOffsetOption { get; }

        /// <summary>
        /// The created timestamp.  This is the timestamp the transaction was created, and may differ from the timestamp of accounting effect for the transaction (ie the property PostingDate).  Always present on transactions.
        /// </summary>
        /// <value>The created timestamp.  This is the timestamp the transaction was created, and may differ from the timestamp of accounting effect for the transaction (ie the property PostingDate).  Always present on transactions.</value>
        /* <example>2021-09-30T08:03:00.123456700Z</example> */
        [JsonPropertyName("CreatedDateTimeOffset")]
        public DateTimeOffset? CreatedDateTimeOffset { get { return this.CreatedDateTimeOffsetOption; } }

        /// <summary>
        /// Used to track the state of CreatedFromImportJournalId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> CreatedFromImportJournalIdOption { get; }

        /// <summary>
        /// The created from import journal identifier, if present.  Provided if this account transaction has been created in Go by an import.
        /// </summary>
        /// <value>The created from import journal identifier, if present.  Provided if this account transaction has been created in Go by an import.</value>
        /* <example>38ecfc1a-bf51-448f-99a8-a61bc5771109</example> */
        [JsonPropertyName("CreatedFromImportJournalId")]
        public Guid? CreatedFromImportJournalId { get { return this.CreatedFromImportJournalIdOption; } }

        /// <summary>
        /// Used to track the state of CurrencyAmount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> CurrencyAmountOption { get; }

        /// <summary>
        /// The currency amount. Differs from Amount if the transaction was posted with a currency other than the client currency.
        /// </summary>
        /// <value>The currency amount. Differs from Amount if the transaction was posted with a currency other than the client currency.</value>
        /* <example>8.5212</example> */
        [JsonPropertyName("CurrencyAmount")]
        public double? CurrencyAmount { get { return this.CurrencyAmountOption; } }

        /// <summary>
        /// Used to track the state of CurrencyCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CurrencyCodeOption { get; }

        /// <summary>
        /// The currency code. Currencies active on the client can be queried using the AccountingSettings service. Currency codes follow the ISO4217 standard.
        /// </summary>
        /// <value>The currency code. Currencies active on the client can be queried using the AccountingSettings service. Currency codes follow the ISO4217 standard.</value>
        /* <example>USD</example> */
        [JsonPropertyName("CurrencyCode")]
        public string? CurrencyCode { get { return this.CurrencyCodeOption; } }

        /// <summary>
        /// Used to track the state of CustomMatchingReference
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CustomMatchingReferenceOption { get; }

        /// <summary>
        /// The custom matching reference set on the transaction. This property will only have value on entries created through the API or Import with CustomMatchingReference specified.  This property is used for matching purposes, where entries posted with a CustomMatchingReference will be matched immediately with existing entries in the sub-ledger that have the same CustomMatchingReference and opposite amount (unless existing entries are already matched out).
        /// </summary>
        /// <value>The custom matching reference set on the transaction. This property will only have value on entries created through the API or Import with CustomMatchingReference specified.  This property is used for matching purposes, where entries posted with a CustomMatchingReference will be matched immediately with existing entries in the sub-ledger that have the same CustomMatchingReference and opposite amount (unless existing entries are already matched out).</value>
        /* <example>123-abc</example> */
        [JsonPropertyName("CustomMatchingReference")]
        public string? CustomMatchingReference { get { return this.CustomMatchingReferenceOption; } }

        /// <summary>
        /// Used to track the state of DepartmentCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DepartmentCodeOption { get; }

        /// <summary>
        /// The department code. Available if the transaction was posted with department.  Departments can be queried and identified using the Department service.
        /// </summary>
        /// <value>The department code. Available if the transaction was posted with department.  Departments can be queried and identified using the Department service.</value>
        /* <example>110</example> */
        [JsonPropertyName("DepartmentCode")]
        public string? DepartmentCode { get { return this.DepartmentCodeOption; } }

        /// <summary>
        /// Used to track the state of DepartmentId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> DepartmentIdOption { get; }

        /// <summary>
        /// The department id. Available if the transaction was posted with department.  Departments can be queried and identified using the Department service.
        /// </summary>
        /// <value>The department id. Available if the transaction was posted with department.  Departments can be queried and identified using the Department service.</value>
        /* <example>123456</example> */
        [JsonPropertyName("DepartmentId")]
        public long? DepartmentId { get { return this.DepartmentIdOption; } }

        /// <summary>
        /// Used to track the state of Dim1Code
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> Dim1CodeOption { get; }

        /// <summary>
        /// The code of the dimension 1 associated with the entry.  Dimension 1-3 are customizable dimensions that can be defined and queried using the CustomDimension- and CustomDimensionValue-services.
        /// </summary>
        /// <value>The code of the dimension 1 associated with the entry.  Dimension 1-3 are customizable dimensions that can be defined and queried using the CustomDimension- and CustomDimensionValue-services.</value>
        /* <example>dimcode111</example> */
        [JsonPropertyName("Dim1Code")]
        public string? Dim1Code { get { return this.Dim1CodeOption; } }

        /// <summary>
        /// Used to track the state of Dim1Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> Dim1IdOption { get; }

        /// <summary>
        /// The id of the dimension 1 associated with the account transaction.
        /// </summary>
        /// <value>The id of the dimension 1 associated with the account transaction.</value>
        /* <example>123456</example> */
        [JsonPropertyName("Dim1Id")]
        public long? Dim1Id { get { return this.Dim1IdOption; } }

        /// <summary>
        /// Used to track the state of Dim2Code
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> Dim2CodeOption { get; }

        /// <summary>
        /// The code of the dimension 2 associated with the account transaction.  Dimension 1-3 are customizable dimensions that can be defined and queried using the CustomDimension- and CustomDimensionValue-services.
        /// </summary>
        /// <value>The code of the dimension 2 associated with the account transaction.  Dimension 1-3 are customizable dimensions that can be defined and queried using the CustomDimension- and CustomDimensionValue-services.</value>
        /* <example>dimcode222</example> */
        [JsonPropertyName("Dim2Code")]
        public string? Dim2Code { get { return this.Dim2CodeOption; } }

        /// <summary>
        /// Used to track the state of Dim2Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> Dim2IdOption { get; }

        /// <summary>
        /// The id of the dimension 2 associated with the account transaction.
        /// </summary>
        /// <value>The id of the dimension 2 associated with the account transaction.</value>
        /* <example>123456</example> */
        [JsonPropertyName("Dim2Id")]
        public long? Dim2Id { get { return this.Dim2IdOption; } }

        /// <summary>
        /// Used to track the state of Dim3Code
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> Dim3CodeOption { get; }

        /// <summary>
        /// The code of the dimension 3 associated with the account transaction.  Dimension 1-3 are customizable dimensions that can be defined and queried using the CustomDimension- and CustomDimensionValue-services.
        /// </summary>
        /// <value>The code of the dimension 3 associated with the account transaction.  Dimension 1-3 are customizable dimensions that can be defined and queried using the CustomDimension- and CustomDimensionValue-services.</value>
        /* <example>dimcode333</example> */
        [JsonPropertyName("Dim3Code")]
        public string? Dim3Code { get { return this.Dim3CodeOption; } }

        /// <summary>
        /// Used to track the state of Dim3Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> Dim3IdOption { get; }

        /// <summary>
        /// The id of the dimension 3 associated with the account transaction.
        /// </summary>
        /// <value>The id of the dimension 3 associated with the account transaction.</value>
        /* <example>123456</example> */
        [JsonPropertyName("Dim3Id")]
        public long? Dim3Id { get { return this.Dim3IdOption; } }

        /// <summary>
        /// Used to track the state of DueDate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTimeOffset?> DueDateOption { get; private set; }

        /// <summary>
        /// The due date of the entry. Relevant only for voucher types IncomingInvoice and IncomingCreditNote. The date represent when the amount is due to be paid to the supplier.
        /// </summary>
        /// <value>The due date of the entry. Relevant only for voucher types IncomingInvoice and IncomingCreditNote. The date represent when the amount is due to be paid to the supplier.</value>
        /* <example>Tue Sep 28 02:00:00 CEST 2021</example> */
        [JsonPropertyName("DueDate")]
        public DateTimeOffset? DueDate { get { return this.DueDateOption; } set { this.DueDateOption = new(value); } }

        /// <summary>
        /// Used to track the state of ExternalImportReference
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ExternalImportReferenceOption { get; }

        /// <summary>
        /// The ExternalImportReference, if set.  This property can be set by integrations posting vouchers in Go, in order to reference the external system and ensure a duplicate check when posting the voucher to Go (only one instance of the reference can exist).  Can be used to correlate/duplicate check transaction.
        /// </summary>
        /// <value>The ExternalImportReference, if set.  This property can be set by integrations posting vouchers in Go, in order to reference the external system and ensure a duplicate check when posting the voucher to Go (only one instance of the reference can exist).  Can be used to correlate/duplicate check transaction.</value>
        /* <example>123abc</example> */
        [JsonPropertyName("ExternalImportReference")]
        public string? ExternalImportReference { get { return this.ExternalImportReferenceOption; } }

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> IdOption { get; }

        /// <summary>
        /// A value that uniquely identifies this (ledger) entry. The Id is assigned by Go when the transactions is posted in Go.  Always present on transactions.
        /// </summary>
        /// <value>A value that uniquely identifies this (ledger) entry. The Id is assigned by Go when the transactions is posted in Go.  Always present on transactions.</value>
        /* <example>476023749</example> */
        [JsonPropertyName("Id")]
        public long? Id { get { return this.IdOption; } }

        /// <summary>
        /// Used to track the state of InvoiceNo
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> InvoiceNoOption { get; }

        /// <summary>
        /// The invoice number, if the entry is an entry with the voucher type IncomingInvoice or IncomingCreditNote.  Be aware that the invoiceNo is a string, so it&#39;s not necessarily a number.
        /// </summary>
        /// <value>The invoice number, if the entry is an entry with the voucher type IncomingInvoice or IncomingCreditNote.  Be aware that the invoiceNo is a string, so it&#39;s not necessarily a number.</value>
        /* <example>15545</example> */
        [JsonPropertyName("InvoiceNo")]
        public string? InvoiceNo { get { return this.InvoiceNoOption; } }

        /// <summary>
        /// Used to track the state of IsCreatedByCurrentIntegration
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsCreatedByCurrentIntegrationOption { get; }

        /// <summary>
        /// A value indicating whether this ledger entry is created by the integration currently communicating with the API.  Will be true for all entries that are created by the same integration user (same Application Key) as the integration currently authorized.  Can be used in filtering if only the current integration&#39;s entries are relevant to report (in simplified queries of payment status of invoices, for instance).
        /// </summary>
        /// <value>A value indicating whether this ledger entry is created by the integration currently communicating with the API.  Will be true for all entries that are created by the same integration user (same Application Key) as the integration currently authorized.  Can be used in filtering if only the current integration&#39;s entries are relevant to report (in simplified queries of payment status of invoices, for instance).</value>
        /* <example>true</example> */
        [JsonPropertyName("IsCreatedByCurrentIntegration")]
        public bool? IsCreatedByCurrentIntegration { get { return this.IsCreatedByCurrentIntegrationOption; } }

        /// <summary>
        /// Used to track the state of IsWriteOff
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsWriteOffOption { get; }

        /// <summary>
        /// A value indicating whether this entry was created by the write off functionality in Go.  Such entries are not payments, but an accounting routine writing off an open item.
        /// </summary>
        /// <value>A value indicating whether this entry was created by the write off functionality in Go.  Such entries are not payments, but an accounting routine writing off an open item.</value>
        /* <example>true</example> */
        [JsonPropertyName("IsWriteOff")]
        public bool? IsWriteOff { get { return this.IsWriteOffOption; } }

        /// <summary>
        /// Used to track the state of LastChangedDateTimeOffset
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTimeOffset?> LastChangedDateTimeOffsetOption { get; }

        /// <summary>
        /// The timestamp of the last change of this entry.  The accounting entry in itself cannot change, but the match state of the sub-ledger entry might change.  Using last changed filtering is one way of retrieving new matched items and as such the payment status of invoices.
        /// </summary>
        /// <value>The timestamp of the last change of this entry.  The accounting entry in itself cannot change, but the match state of the sub-ledger entry might change.  Using last changed filtering is one way of retrieving new matched items and as such the payment status of invoices.</value>
        /* <example>2021-09-30T08:03:00.123456700Z</example> */
        [JsonPropertyName("LastChangedDateTimeOffset")]
        public DateTimeOffset? LastChangedDateTimeOffset { get { return this.LastChangedDateTimeOffsetOption; } }

        /// <summary>
        /// Used to track the state of LocationCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LocationCodeOption { get; }

        /// <summary>
        /// The code of the location dimension associated with the entry, if set.
        /// </summary>
        /// <value>The code of the location dimension associated with the entry, if set.</value>
        /* <example>L1337</example> */
        [JsonPropertyName("LocationCode")]
        public string? LocationCode { get { return this.LocationCodeOption; } }

        /// <summary>
        /// Used to track the state of LocationId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> LocationIdOption { get; }

        /// <summary>
        /// The id of the location dimension associated with the entry, if location code is set.
        /// </summary>
        /// <value>The id of the location dimension associated with the entry, if location code is set.</value>
        /* <example>12345</example> */
        [JsonPropertyName("LocationId")]
        public long? LocationId { get { return this.LocationIdOption; } }

        /// <summary>
        /// Used to track the state of MatchId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> MatchIdOption { get; }

        /// <summary>
        /// The match identifier on the entry, if it is matched with one or more other entries. All sub-ledger entries that are matched together share the same matchId.
        /// </summary>
        /// <value>The match identifier on the entry, if it is matched with one or more other entries. All sub-ledger entries that are matched together share the same matchId.</value>
        /* <example>123456</example> */
        [JsonPropertyName("MatchId")]
        public long? MatchId { get { return this.MatchIdOption; } }

        /// <summary>
        /// Used to track the state of PostingDate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTimeOffset?> PostingDateOption { get; }

        /// <summary>
        /// The posting date.  This is the date of effect in the accounting system for the Amount and CurrencyAmount (also the currency conversion date used by Go if the currency rate was not set explicit when posted).  Always present on transactions.
        /// </summary>
        /// <value>The posting date.  This is the date of effect in the accounting system for the Amount and CurrencyAmount (also the currency conversion date used by Go if the currency rate was not set explicit when posted).  Always present on transactions.</value>
        /* <example>Tue Sep 28 02:00:00 CEST 2021</example> */
        [JsonPropertyName("PostingDate")]
        public DateTimeOffset? PostingDate { get { return this.PostingDateOption; } }

        /// <summary>
        /// Used to track the state of ProjectCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ProjectCodeOption { get; }

        /// <summary>
        /// The project code. Available if the transaction was posted with project.  Projects can be queried and identified using the Project service.
        /// </summary>
        /// <value>The project code. Available if the transaction was posted with project.  Projects can be queried and identified using the Project service.</value>
        /* <example>100</example> */
        [JsonPropertyName("ProjectCode")]
        public string? ProjectCode { get { return this.ProjectCodeOption; } }

        /// <summary>
        /// Used to track the state of ProjectId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> ProjectIdOption { get; }

        /// <summary>
        /// The project id. Available if the transaction was posted with project.  Projects can be queried and identified using the Project service.
        /// </summary>
        /// <value>The project id. Available if the transaction was posted with project.  Projects can be queried and identified using the Project service.</value>
        /* <example>123456</example> */
        [JsonPropertyName("ProjectId")]
        public long? ProjectId { get { return this.ProjectIdOption; } }

        /// <summary>
        /// Used to track the state of SupplierAccountNo
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> SupplierAccountNoOption { get; }

        /// <summary>
        /// The supplier account number this sub-ledger entry is posted on.  SupplierAccountNo will also represent the Supplier number.  Suppliers can be queried and identified using the Supplier service.
        /// </summary>
        /// <value>The supplier account number this sub-ledger entry is posted on.  SupplierAccountNo will also represent the Supplier number.  Suppliers can be queried and identified using the Supplier service.</value>
        /* <example>20000</example> */
        [JsonPropertyName("SupplierAccountNo")]
        public long? SupplierAccountNo { get { return this.SupplierAccountNoOption; } }

        /// <summary>
        /// Used to track the state of SupplierExternalNo
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> SupplierExternalNoOption { get; }

        /// <summary>
        /// The external number of the supplier of this sub-ledger entry.  An external number set on the supplier is often used to reference the supplier number in the external system, if the supplier numbers are not kept in 1:1 sync between Go and the external system.  The field is available in the GUI with the name External Code.  Suppliers can be queried and identified using the Supplier service.
        /// </summary>
        /// <value>The external number of the supplier of this sub-ledger entry.  An external number set on the supplier is often used to reference the supplier number in the external system, if the supplier numbers are not kept in 1:1 sync between Go and the external system.  The field is available in the GUI with the name External Code.  Suppliers can be queried and identified using the Supplier service.</value>
        /* <example>12345</example> */
        [JsonPropertyName("SupplierExternalNo")]
        public long? SupplierExternalNo { get { return this.SupplierExternalNoOption; } }

        /// <summary>
        /// Used to track the state of SupplierId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> SupplierIdOption { get; }

        /// <summary>
        /// The id of the supplier of this sub-ledger entry.  Suppliers can be queried and identified using the Supplier service.
        /// </summary>
        /// <value>The id of the supplier of this sub-ledger entry.  Suppliers can be queried and identified using the Supplier service.</value>
        /* <example>123456</example> */
        [JsonPropertyName("SupplierId")]
        public long? SupplierId { get { return this.SupplierIdOption; } }

        /// <summary>
        /// Used to track the state of SupplierName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SupplierNameOption { get; }

        /// <summary>
        /// The name of the supplier of this sub-ledger entry.  Suppliers can be queried and identified using the Supplier service.
        /// </summary>
        /// <value>The name of the supplier of this sub-ledger entry.  Suppliers can be queried and identified using the Supplier service.</value>
        /* <example>Coca-Cola AS</example> */
        [JsonPropertyName("SupplierName")]
        public string? SupplierName { get { return this.SupplierNameOption; } }

        /// <summary>
        /// Used to track the state of VoucherDate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTimeOffset?> VoucherDateOption { get; }

        /// <summary>
        /// The date of the voucher.  This represents the date of the voucher, the document date of an invoice for instance,  and may differ from the transaction dates for the voucher.  Always present on transactions.
        /// </summary>
        /// <value>The date of the voucher.  This represents the date of the voucher, the document date of an invoice for instance,  and may differ from the transaction dates for the voucher.  Always present on transactions.</value>
        /* <example>Sat Jul 25 02:00:00 CEST 2020</example> */
        [JsonPropertyName("VoucherDate")]
        public DateTimeOffset? VoucherDate { get { return this.VoucherDateOption; } }

        /// <summary>
        /// Used to track the state of VoucherId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> VoucherIdOption { get; }

        /// <summary>
        /// The voucher identifier.  The Id is assigned by Go when the voucher is created, and is shared by all transactions within the same voucher.  Always present on transactions.
        /// </summary>
        /// <value>The voucher identifier.  The Id is assigned by Go when the voucher is created, and is shared by all transactions within the same voucher.  Always present on transactions.</value>
        /* <example>ee373540-ca8d-4562-8fb6-6fb52de47722</example> */
        [JsonPropertyName("VoucherId")]
        public Guid? VoucherId { get { return this.VoucherIdOption; } }

        /// <summary>
        /// Used to track the state of VoucherNo
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> VoucherNoOption { get; }

        /// <summary>
        /// The voucher number.  This is the voucher number assigned by Go when the voucher was posted.  Voucher numbers are assigned by Go in sequence.  Always present on transactions.
        /// </summary>
        /// <value>The voucher number.  This is the voucher number assigned by Go when the voucher was posted.  Voucher numbers are assigned by Go in sequence.  Always present on transactions.</value>
        /* <example>15545</example> */
        [JsonPropertyName("VoucherNo")]
        public long? VoucherNo { get { return this.VoucherNoOption; } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SupplierLedgerEntryDto {\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Balance: ").Append(Balance).Append("\n");
            sb.Append("  Cid: ").Append(Cid).Append("\n");
            sb.Append("  CreatedDateTimeOffset: ").Append(CreatedDateTimeOffset).Append("\n");
            sb.Append("  CreatedFromImportJournalId: ").Append(CreatedFromImportJournalId).Append("\n");
            sb.Append("  CurrencyAmount: ").Append(CurrencyAmount).Append("\n");
            sb.Append("  CurrencyCode: ").Append(CurrencyCode).Append("\n");
            sb.Append("  CustomMatchingReference: ").Append(CustomMatchingReference).Append("\n");
            sb.Append("  DepartmentCode: ").Append(DepartmentCode).Append("\n");
            sb.Append("  DepartmentId: ").Append(DepartmentId).Append("\n");
            sb.Append("  Dim1Code: ").Append(Dim1Code).Append("\n");
            sb.Append("  Dim1Id: ").Append(Dim1Id).Append("\n");
            sb.Append("  Dim2Code: ").Append(Dim2Code).Append("\n");
            sb.Append("  Dim2Id: ").Append(Dim2Id).Append("\n");
            sb.Append("  Dim3Code: ").Append(Dim3Code).Append("\n");
            sb.Append("  Dim3Id: ").Append(Dim3Id).Append("\n");
            sb.Append("  DueDate: ").Append(DueDate).Append("\n");
            sb.Append("  ExternalImportReference: ").Append(ExternalImportReference).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  InvoiceNo: ").Append(InvoiceNo).Append("\n");
            sb.Append("  IsCreatedByCurrentIntegration: ").Append(IsCreatedByCurrentIntegration).Append("\n");
            sb.Append("  IsWriteOff: ").Append(IsWriteOff).Append("\n");
            sb.Append("  LastChangedDateTimeOffset: ").Append(LastChangedDateTimeOffset).Append("\n");
            sb.Append("  LocationCode: ").Append(LocationCode).Append("\n");
            sb.Append("  LocationId: ").Append(LocationId).Append("\n");
            sb.Append("  MatchId: ").Append(MatchId).Append("\n");
            sb.Append("  PostingDate: ").Append(PostingDate).Append("\n");
            sb.Append("  ProjectCode: ").Append(ProjectCode).Append("\n");
            sb.Append("  ProjectId: ").Append(ProjectId).Append("\n");
            sb.Append("  SupplierAccountNo: ").Append(SupplierAccountNo).Append("\n");
            sb.Append("  SupplierExternalNo: ").Append(SupplierExternalNo).Append("\n");
            sb.Append("  SupplierId: ").Append(SupplierId).Append("\n");
            sb.Append("  SupplierName: ").Append(SupplierName).Append("\n");
            sb.Append("  VoucherDate: ").Append(VoucherDate).Append("\n");
            sb.Append("  VoucherId: ").Append(VoucherId).Append("\n");
            sb.Append("  VoucherNo: ").Append(VoucherNo).Append("\n");
            sb.Append("  VoucherType: ").Append(VoucherType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SupplierLedgerEntryDto" />
    /// </summary>
    public class SupplierLedgerEntryDtoJsonConverter : JsonConverter<SupplierLedgerEntryDto>
    {
        /// <summary>
        /// The format to use to serialize CreatedDateTimeOffset
        /// </summary>
        public static string CreatedDateTimeOffsetFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize DueDate
        /// </summary>
        public static string DueDateFormat { get; set; } = "yyyy'-'MM'-'dd";

        /// <summary>
        /// The format to use to serialize LastChangedDateTimeOffset
        /// </summary>
        public static string LastChangedDateTimeOffsetFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize PostingDate
        /// </summary>
        public static string PostingDateFormat { get; set; } = "yyyy'-'MM'-'dd";

        /// <summary>
        /// The format to use to serialize VoucherDate
        /// </summary>
        public static string VoucherDateFormat { get; set; } = "yyyy'-'MM'-'dd";

        /// <summary>
        /// Deserializes json to <see cref="SupplierLedgerEntryDto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SupplierLedgerEntryDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<double?> amount = default;
            Option<double?> balance = default;
            Option<string?> cid = default;
            Option<DateTimeOffset?> createdDateTimeOffset = default;
            Option<Guid?> createdFromImportJournalId = default;
            Option<double?> currencyAmount = default;
            Option<string?> currencyCode = default;
            Option<string?> customMatchingReference = default;
            Option<string?> departmentCode = default;
            Option<long?> departmentId = default;
            Option<string?> dim1Code = default;
            Option<long?> dim1Id = default;
            Option<string?> dim2Code = default;
            Option<long?> dim2Id = default;
            Option<string?> dim3Code = default;
            Option<long?> dim3Id = default;
            Option<DateTimeOffset?> dueDate = default;
            Option<string?> externalImportReference = default;
            Option<long?> id = default;
            Option<string?> invoiceNo = default;
            Option<bool?> isCreatedByCurrentIntegration = default;
            Option<bool?> isWriteOff = default;
            Option<DateTimeOffset?> lastChangedDateTimeOffset = default;
            Option<string?> locationCode = default;
            Option<long?> locationId = default;
            Option<long?> matchId = default;
            Option<DateTimeOffset?> postingDate = default;
            Option<string?> projectCode = default;
            Option<long?> projectId = default;
            Option<long?> supplierAccountNo = default;
            Option<long?> supplierExternalNo = default;
            Option<long?> supplierId = default;
            Option<string?> supplierName = default;
            Option<DateTimeOffset?> voucherDate = default;
            Option<Guid?> voucherId = default;
            Option<long?> voucherNo = default;
            Option<VoucherType?> voucherType = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "Amount":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                amount = new Option<double?>(utf8JsonReader.GetDouble());
                            break;
                        case "Balance":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                balance = new Option<double?>(utf8JsonReader.GetDouble());
                            break;
                        case "Cid":
                            cid = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "CreatedDateTimeOffset":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                createdDateTimeOffset = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "CreatedFromImportJournalId":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                createdFromImportJournalId = new Option<Guid?>(utf8JsonReader.GetGuid());
                            break;
                        case "CurrencyAmount":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                currencyAmount = new Option<double?>(utf8JsonReader.GetDouble());
                            break;
                        case "CurrencyCode":
                            currencyCode = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "CustomMatchingReference":
                            customMatchingReference = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "DepartmentCode":
                            departmentCode = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "DepartmentId":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                departmentId = new Option<long?>(utf8JsonReader.GetInt64());
                            break;
                        case "Dim1Code":
                            dim1Code = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "Dim1Id":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                dim1Id = new Option<long?>(utf8JsonReader.GetInt64());
                            break;
                        case "Dim2Code":
                            dim2Code = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "Dim2Id":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                dim2Id = new Option<long?>(utf8JsonReader.GetInt64());
                            break;
                        case "Dim3Code":
                            dim3Code = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "Dim3Id":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                dim3Id = new Option<long?>(utf8JsonReader.GetInt64());
                            break;
                        case "DueDate":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                dueDate = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTime?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "ExternalImportReference":
                            externalImportReference = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "Id":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                id = new Option<long?>(utf8JsonReader.GetInt64());
                            break;
                        case "InvoiceNo":
                            invoiceNo = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "IsCreatedByCurrentIntegration":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                isCreatedByCurrentIntegration = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        case "IsWriteOff":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                isWriteOff = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        case "LastChangedDateTimeOffset":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                lastChangedDateTimeOffset = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "LocationCode":
                            locationCode = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "LocationId":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                locationId = new Option<long?>(utf8JsonReader.GetInt64());
                            break;
                        case "MatchId":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                matchId = new Option<long?>(utf8JsonReader.GetInt64());
                            break;
                        case "PostingDate":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                postingDate = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "ProjectCode":
                            projectCode = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "ProjectId":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                projectId = new Option<long?>(utf8JsonReader.GetInt64());
                            break;
                        case "SupplierAccountNo":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                supplierAccountNo = new Option<long?>(utf8JsonReader.GetInt64());
                            break;
                        case "SupplierExternalNo":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                supplierExternalNo = new Option<long?>(utf8JsonReader.GetInt64());
                            break;
                        case "SupplierId":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                supplierId = new Option<long?>(utf8JsonReader.GetInt64());
                            break;
                        case "SupplierName":
                            supplierName = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "VoucherDate":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                voucherDate = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "VoucherId":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                voucherId = new Option<Guid?>(utf8JsonReader.GetGuid());
                            break;
                        case "VoucherNo":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                voucherNo = new Option<long?>(utf8JsonReader.GetInt64());
                            break;
                        case "VoucherType":
                            string? voucherTypeRawValue = utf8JsonReader.GetString();
                            if (voucherTypeRawValue != null)
                                voucherType = new Option<VoucherType?>(VoucherTypeValueConverter.FromStringOrDefault(voucherTypeRawValue));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (amount.IsSet && amount.Value == null)
                throw new ArgumentNullException(nameof(amount), "Property is not nullable for class SupplierLedgerEntryDto.");

            if (balance.IsSet && balance.Value == null)
                throw new ArgumentNullException(nameof(balance), "Property is not nullable for class SupplierLedgerEntryDto.");

            if (createdDateTimeOffset.IsSet && createdDateTimeOffset.Value == null)
                throw new ArgumentNullException(nameof(createdDateTimeOffset), "Property is not nullable for class SupplierLedgerEntryDto.");

            if (currencyAmount.IsSet && currencyAmount.Value == null)
                throw new ArgumentNullException(nameof(currencyAmount), "Property is not nullable for class SupplierLedgerEntryDto.");

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class SupplierLedgerEntryDto.");

            if (lastChangedDateTimeOffset.IsSet && lastChangedDateTimeOffset.Value == null)
                throw new ArgumentNullException(nameof(lastChangedDateTimeOffset), "Property is not nullable for class SupplierLedgerEntryDto.");

            if (postingDate.IsSet && postingDate.Value == null)
                throw new ArgumentNullException(nameof(postingDate), "Property is not nullable for class SupplierLedgerEntryDto.");

            if (voucherDate.IsSet && voucherDate.Value == null)
                throw new ArgumentNullException(nameof(voucherDate), "Property is not nullable for class SupplierLedgerEntryDto.");

            if (voucherId.IsSet && voucherId.Value == null)
                throw new ArgumentNullException(nameof(voucherId), "Property is not nullable for class SupplierLedgerEntryDto.");

            if (voucherNo.IsSet && voucherNo.Value == null)
                throw new ArgumentNullException(nameof(voucherNo), "Property is not nullable for class SupplierLedgerEntryDto.");

            return new SupplierLedgerEntryDto(amount, balance, cid, createdDateTimeOffset, createdFromImportJournalId, currencyAmount, currencyCode, customMatchingReference, departmentCode, departmentId, dim1Code, dim1Id, dim2Code, dim2Id, dim3Code, dim3Id, dueDate, externalImportReference, id, invoiceNo, isCreatedByCurrentIntegration, isWriteOff, lastChangedDateTimeOffset, locationCode, locationId, matchId, postingDate, projectCode, projectId, supplierAccountNo, supplierExternalNo, supplierId, supplierName, voucherDate, voucherId, voucherNo, voucherType);
        }

        /// <summary>
        /// Serializes a <see cref="SupplierLedgerEntryDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="supplierLedgerEntryDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SupplierLedgerEntryDto supplierLedgerEntryDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, supplierLedgerEntryDto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SupplierLedgerEntryDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="supplierLedgerEntryDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SupplierLedgerEntryDto supplierLedgerEntryDto, JsonSerializerOptions jsonSerializerOptions)
        {
            if (supplierLedgerEntryDto.AmountOption.IsSet)
                writer.WriteNumber("Amount", supplierLedgerEntryDto.AmountOption.Value!.Value);

            if (supplierLedgerEntryDto.BalanceOption.IsSet)
                writer.WriteNumber("Balance", supplierLedgerEntryDto.BalanceOption.Value!.Value);

            if (supplierLedgerEntryDto.CidOption.IsSet)
                if (supplierLedgerEntryDto.CidOption.Value != null)
                    writer.WriteString("Cid", supplierLedgerEntryDto.Cid);
                else
                    writer.WriteNull("Cid");

            if (supplierLedgerEntryDto.CreatedDateTimeOffsetOption.IsSet)
                writer.WriteString("CreatedDateTimeOffset", supplierLedgerEntryDto.CreatedDateTimeOffsetOption.Value!.Value.ToString(CreatedDateTimeOffsetFormat));

            if (supplierLedgerEntryDto.CreatedFromImportJournalIdOption.IsSet)
                if (supplierLedgerEntryDto.CreatedFromImportJournalIdOption.Value != null)
                    writer.WriteString("CreatedFromImportJournalId", supplierLedgerEntryDto.CreatedFromImportJournalIdOption.Value!.Value);
                else
                    writer.WriteNull("CreatedFromImportJournalId");

            if (supplierLedgerEntryDto.CurrencyAmountOption.IsSet)
                writer.WriteNumber("CurrencyAmount", supplierLedgerEntryDto.CurrencyAmountOption.Value!.Value);

            if (supplierLedgerEntryDto.CurrencyCodeOption.IsSet)
                if (supplierLedgerEntryDto.CurrencyCodeOption.Value != null)
                    writer.WriteString("CurrencyCode", supplierLedgerEntryDto.CurrencyCode);
                else
                    writer.WriteNull("CurrencyCode");

            if (supplierLedgerEntryDto.CustomMatchingReferenceOption.IsSet)
                if (supplierLedgerEntryDto.CustomMatchingReferenceOption.Value != null)
                    writer.WriteString("CustomMatchingReference", supplierLedgerEntryDto.CustomMatchingReference);
                else
                    writer.WriteNull("CustomMatchingReference");

            if (supplierLedgerEntryDto.DepartmentCodeOption.IsSet)
                if (supplierLedgerEntryDto.DepartmentCodeOption.Value != null)
                    writer.WriteString("DepartmentCode", supplierLedgerEntryDto.DepartmentCode);
                else
                    writer.WriteNull("DepartmentCode");

            if (supplierLedgerEntryDto.DepartmentIdOption.IsSet)
                if (supplierLedgerEntryDto.DepartmentIdOption.Value != null)
                    writer.WriteNumber("DepartmentId", supplierLedgerEntryDto.DepartmentIdOption.Value!.Value);
                else
                    writer.WriteNull("DepartmentId");

            if (supplierLedgerEntryDto.Dim1CodeOption.IsSet)
                if (supplierLedgerEntryDto.Dim1CodeOption.Value != null)
                    writer.WriteString("Dim1Code", supplierLedgerEntryDto.Dim1Code);
                else
                    writer.WriteNull("Dim1Code");

            if (supplierLedgerEntryDto.Dim1IdOption.IsSet)
                if (supplierLedgerEntryDto.Dim1IdOption.Value != null)
                    writer.WriteNumber("Dim1Id", supplierLedgerEntryDto.Dim1IdOption.Value!.Value);
                else
                    writer.WriteNull("Dim1Id");

            if (supplierLedgerEntryDto.Dim2CodeOption.IsSet)
                if (supplierLedgerEntryDto.Dim2CodeOption.Value != null)
                    writer.WriteString("Dim2Code", supplierLedgerEntryDto.Dim2Code);
                else
                    writer.WriteNull("Dim2Code");

            if (supplierLedgerEntryDto.Dim2IdOption.IsSet)
                if (supplierLedgerEntryDto.Dim2IdOption.Value != null)
                    writer.WriteNumber("Dim2Id", supplierLedgerEntryDto.Dim2IdOption.Value!.Value);
                else
                    writer.WriteNull("Dim2Id");

            if (supplierLedgerEntryDto.Dim3CodeOption.IsSet)
                if (supplierLedgerEntryDto.Dim3CodeOption.Value != null)
                    writer.WriteString("Dim3Code", supplierLedgerEntryDto.Dim3Code);
                else
                    writer.WriteNull("Dim3Code");

            if (supplierLedgerEntryDto.Dim3IdOption.IsSet)
                if (supplierLedgerEntryDto.Dim3IdOption.Value != null)
                    writer.WriteNumber("Dim3Id", supplierLedgerEntryDto.Dim3IdOption.Value!.Value);
                else
                    writer.WriteNull("Dim3Id");

            if (supplierLedgerEntryDto.DueDateOption.IsSet)
                if (supplierLedgerEntryDto.DueDateOption.Value != null)
                    writer.WriteString("DueDate", supplierLedgerEntryDto.DueDateOption.Value!.Value.ToString(DueDateFormat));
                else
                    writer.WriteNull("DueDate");

            if (supplierLedgerEntryDto.ExternalImportReferenceOption.IsSet)
                if (supplierLedgerEntryDto.ExternalImportReferenceOption.Value != null)
                    writer.WriteString("ExternalImportReference", supplierLedgerEntryDto.ExternalImportReference);
                else
                    writer.WriteNull("ExternalImportReference");

            if (supplierLedgerEntryDto.IdOption.IsSet)
                writer.WriteNumber("Id", supplierLedgerEntryDto.IdOption.Value!.Value);

            if (supplierLedgerEntryDto.InvoiceNoOption.IsSet)
                if (supplierLedgerEntryDto.InvoiceNoOption.Value != null)
                    writer.WriteString("InvoiceNo", supplierLedgerEntryDto.InvoiceNo);
                else
                    writer.WriteNull("InvoiceNo");

            if (supplierLedgerEntryDto.IsCreatedByCurrentIntegrationOption.IsSet)
                if (supplierLedgerEntryDto.IsCreatedByCurrentIntegrationOption.Value != null)
                    writer.WriteBoolean("IsCreatedByCurrentIntegration", supplierLedgerEntryDto.IsCreatedByCurrentIntegrationOption.Value!.Value);
                else
                    writer.WriteNull("IsCreatedByCurrentIntegration");

            if (supplierLedgerEntryDto.IsWriteOffOption.IsSet)
                if (supplierLedgerEntryDto.IsWriteOffOption.Value != null)
                    writer.WriteBoolean("IsWriteOff", supplierLedgerEntryDto.IsWriteOffOption.Value!.Value);
                else
                    writer.WriteNull("IsWriteOff");

            if (supplierLedgerEntryDto.LastChangedDateTimeOffsetOption.IsSet)
                writer.WriteString("LastChangedDateTimeOffset", supplierLedgerEntryDto.LastChangedDateTimeOffsetOption.Value!.Value.ToString(LastChangedDateTimeOffsetFormat));

            if (supplierLedgerEntryDto.LocationCodeOption.IsSet)
                if (supplierLedgerEntryDto.LocationCodeOption.Value != null)
                    writer.WriteString("LocationCode", supplierLedgerEntryDto.LocationCode);
                else
                    writer.WriteNull("LocationCode");

            if (supplierLedgerEntryDto.LocationIdOption.IsSet)
                if (supplierLedgerEntryDto.LocationIdOption.Value != null)
                    writer.WriteNumber("LocationId", supplierLedgerEntryDto.LocationIdOption.Value!.Value);
                else
                    writer.WriteNull("LocationId");

            if (supplierLedgerEntryDto.MatchIdOption.IsSet)
                if (supplierLedgerEntryDto.MatchIdOption.Value != null)
                    writer.WriteNumber("MatchId", supplierLedgerEntryDto.MatchIdOption.Value!.Value);
                else
                    writer.WriteNull("MatchId");

            if (supplierLedgerEntryDto.PostingDateOption.IsSet)
                writer.WriteString("PostingDate", supplierLedgerEntryDto.PostingDateOption.Value!.Value.ToString(PostingDateFormat));

            if (supplierLedgerEntryDto.ProjectCodeOption.IsSet)
                if (supplierLedgerEntryDto.ProjectCodeOption.Value != null)
                    writer.WriteString("ProjectCode", supplierLedgerEntryDto.ProjectCode);
                else
                    writer.WriteNull("ProjectCode");

            if (supplierLedgerEntryDto.ProjectIdOption.IsSet)
                if (supplierLedgerEntryDto.ProjectIdOption.Value != null)
                    writer.WriteNumber("ProjectId", supplierLedgerEntryDto.ProjectIdOption.Value!.Value);
                else
                    writer.WriteNull("ProjectId");

            if (supplierLedgerEntryDto.SupplierAccountNoOption.IsSet)
                if (supplierLedgerEntryDto.SupplierAccountNoOption.Value != null)
                    writer.WriteNumber("SupplierAccountNo", supplierLedgerEntryDto.SupplierAccountNoOption.Value!.Value);
                else
                    writer.WriteNull("SupplierAccountNo");

            if (supplierLedgerEntryDto.SupplierExternalNoOption.IsSet)
                if (supplierLedgerEntryDto.SupplierExternalNoOption.Value != null)
                    writer.WriteNumber("SupplierExternalNo", supplierLedgerEntryDto.SupplierExternalNoOption.Value!.Value);
                else
                    writer.WriteNull("SupplierExternalNo");

            if (supplierLedgerEntryDto.SupplierIdOption.IsSet)
                if (supplierLedgerEntryDto.SupplierIdOption.Value != null)
                    writer.WriteNumber("SupplierId", supplierLedgerEntryDto.SupplierIdOption.Value!.Value);
                else
                    writer.WriteNull("SupplierId");

            if (supplierLedgerEntryDto.SupplierNameOption.IsSet)
                if (supplierLedgerEntryDto.SupplierNameOption.Value != null)
                    writer.WriteString("SupplierName", supplierLedgerEntryDto.SupplierName);
                else
                    writer.WriteNull("SupplierName");

            if (supplierLedgerEntryDto.VoucherDateOption.IsSet)
                writer.WriteString("VoucherDate", supplierLedgerEntryDto.VoucherDateOption.Value!.Value.ToString(VoucherDateFormat));

            if (supplierLedgerEntryDto.VoucherIdOption.IsSet)
                writer.WriteString("VoucherId", supplierLedgerEntryDto.VoucherIdOption.Value!.Value);

            if (supplierLedgerEntryDto.VoucherNoOption.IsSet)
                writer.WriteNumber("VoucherNo", supplierLedgerEntryDto.VoucherNoOption.Value!.Value);

            if (supplierLedgerEntryDto.VoucherTypeOption.IsSet)
                if (supplierLedgerEntryDto.VoucherTypeOption!.Value != null)
                {
                    var voucherTypeRawValue = VoucherTypeValueConverter.ToJsonValue(supplierLedgerEntryDto.VoucherTypeOption.Value!.Value);
                    writer.WriteString("VoucherType", voucherTypeRawValue);
                }
                else
                    writer.WriteNull("VoucherType");
        }
    }
}
