/*
 * merged spec
 *
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PowerOfficeGoV2.Model;
using PowerOfficeGoV2.Client;
using System.Reflection;

namespace PowerOfficeGoV2.Test.Model
{
    /// <summary>
    ///  Class for testing CustomDimensionPostDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomDimensionPostDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomDimensionPostDto
        //private CustomDimensionPostDto instance;

        public CustomDimensionPostDtoTests()
        {
            // TODO uncomment below to create an instance of CustomDimensionPostDto
            //instance = new CustomDimensionPostDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomDimensionPostDto
        /// </summary>
        [Fact]
        public void CustomDimensionPostDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomDimensionPostDto
            //Assert.IsType<CustomDimensionPostDto>(instance);
        }

        /// <summary>
        /// Test the property 'Ordinal'
        /// </summary>
        [Fact]
        public void OrdinalTest()
        {
            // TODO unit test for the property 'Ordinal'
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'ExternalImportReference'
        /// </summary>
        [Fact]
        public void ExternalImportReferenceTest()
        {
            // TODO unit test for the property 'ExternalImportReference'
        }

        /// <summary>
        /// Test the property 'IsActive'
        /// </summary>
        [Fact]
        public void IsActiveTest()
        {
            // TODO unit test for the property 'IsActive'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
    }
}
