/*
 * merged spec
 *
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PowerOfficeGoV2.Model;
using PowerOfficeGoV2.Client;
using System.Reflection;

namespace PowerOfficeGoV2.Test.Model
{
    /// <summary>
    ///  Class for testing DeliveryTermDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeliveryTermDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DeliveryTermDto
        //private DeliveryTermDto instance;

        public DeliveryTermDtoTests()
        {
            // TODO uncomment below to create an instance of DeliveryTermDto
            //instance = new DeliveryTermDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DeliveryTermDto
        /// </summary>
        [Fact]
        public void DeliveryTermDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" DeliveryTermDto
            //Assert.IsType<DeliveryTermDto>(instance);
        }

        /// <summary>
        /// Test the property 'CreatedDateTimeOffset'
        /// </summary>
        [Fact]
        public void CreatedDateTimeOffsetTest()
        {
            // TODO unit test for the property 'CreatedDateTimeOffset'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'IsDefault'
        /// </summary>
        [Fact]
        public void IsDefaultTest()
        {
            // TODO unit test for the property 'IsDefault'
        }

        /// <summary>
        /// Test the property 'LastChangedDateTimeOffset'
        /// </summary>
        [Fact]
        public void LastChangedDateTimeOffsetTest()
        {
            // TODO unit test for the property 'LastChangedDateTimeOffset'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
    }
}
