/*
 * merged spec
 *
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PowerOfficeGoV2.Model;
using PowerOfficeGoV2.Client;
using System.Reflection;

namespace PowerOfficeGoV2.Test.Model
{
    /// <summary>
    ///  Class for testing EmploymentFormType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EmploymentFormTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EmploymentFormType
        //private EmploymentFormType instance;

        public EmploymentFormTypeTests()
        {
            // TODO uncomment below to create an instance of EmploymentFormType
            //instance = new EmploymentFormType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmploymentFormType
        /// </summary>
        [Fact]
        public void EmploymentFormTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" EmploymentFormType
            //Assert.IsType<EmploymentFormType>(instance);
        }
    }
}
