/*
 * merged spec
 *
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PowerOfficeGoV2.Model;
using PowerOfficeGoV2.Client;
using System.Reflection;

namespace PowerOfficeGoV2.Test.Model
{
    /// <summary>
    ///  Class for testing EmploymentSalaryDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EmploymentSalaryDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EmploymentSalaryDto
        //private EmploymentSalaryDto instance;

        public EmploymentSalaryDtoTests()
        {
            // TODO uncomment below to create an instance of EmploymentSalaryDto
            //instance = new EmploymentSalaryDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmploymentSalaryDto
        /// </summary>
        [Fact]
        public void EmploymentSalaryDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" EmploymentSalaryDto
            //Assert.IsType<EmploymentSalaryDto>(instance);
        }

        /// <summary>
        /// Test the property 'AnnualSalary'
        /// </summary>
        [Fact]
        public void AnnualSalaryTest()
        {
            // TODO unit test for the property 'AnnualSalary'
        }

        /// <summary>
        /// Test the property 'CreatedDateTimeOffset'
        /// </summary>
        [Fact]
        public void CreatedDateTimeOffsetTest()
        {
            // TODO unit test for the property 'CreatedDateTimeOffset'
        }

        /// <summary>
        /// Test the property 'EmployeeId'
        /// </summary>
        [Fact]
        public void EmployeeIdTest()
        {
            // TODO unit test for the property 'EmployeeId'
        }

        /// <summary>
        /// Test the property 'EmploymentId'
        /// </summary>
        [Fact]
        public void EmploymentIdTest()
        {
            // TODO unit test for the property 'EmploymentId'
        }

        /// <summary>
        /// Test the property 'FromDate'
        /// </summary>
        [Fact]
        public void FromDateTest()
        {
            // TODO unit test for the property 'FromDate'
        }

        /// <summary>
        /// Test the property 'HourlyRate'
        /// </summary>
        [Fact]
        public void HourlyRateTest()
        {
            // TODO unit test for the property 'HourlyRate'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'LastChangedDateTimeOffset'
        /// </summary>
        [Fact]
        public void LastChangedDateTimeOffsetTest()
        {
            // TODO unit test for the property 'LastChangedDateTimeOffset'
        }

        /// <summary>
        /// Test the property 'RemunerationType'
        /// </summary>
        [Fact]
        public void RemunerationTypeTest()
        {
            // TODO unit test for the property 'RemunerationType'
        }
    }
}
