/*
 * merged spec
 *
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PowerOfficeGoV2.Model;
using PowerOfficeGoV2.Client;
using System.Reflection;

namespace PowerOfficeGoV2.Test.Model
{
    /// <summary>
    ///  Class for testing OutgoingInvoiceVoucherDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OutgoingInvoiceVoucherDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OutgoingInvoiceVoucherDto
        //private OutgoingInvoiceVoucherDto instance;

        public OutgoingInvoiceVoucherDtoTests()
        {
            // TODO uncomment below to create an instance of OutgoingInvoiceVoucherDto
            //instance = new OutgoingInvoiceVoucherDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OutgoingInvoiceVoucherDto
        /// </summary>
        [Fact]
        public void OutgoingInvoiceVoucherDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" OutgoingInvoiceVoucherDto
            //Assert.IsType<OutgoingInvoiceVoucherDto>(instance);
        }

        /// <summary>
        /// Test the property 'Cid'
        /// </summary>
        [Fact]
        public void CidTest()
        {
            // TODO unit test for the property 'Cid'
        }

        /// <summary>
        /// Test the property 'ContractNo'
        /// </summary>
        [Fact]
        public void ContractNoTest()
        {
            // TODO unit test for the property 'ContractNo'
        }

        /// <summary>
        /// Test the property 'CreatedDateTimeOffset'
        /// </summary>
        [Fact]
        public void CreatedDateTimeOffsetTest()
        {
            // TODO unit test for the property 'CreatedDateTimeOffset'
        }

        /// <summary>
        /// Test the property 'CurrencyAmount'
        /// </summary>
        [Fact]
        public void CurrencyAmountTest()
        {
            // TODO unit test for the property 'CurrencyAmount'
        }

        /// <summary>
        /// Test the property 'CurrencyCode'
        /// </summary>
        [Fact]
        public void CurrencyCodeTest()
        {
            // TODO unit test for the property 'CurrencyCode'
        }

        /// <summary>
        /// Test the property 'CurrencyExchangeRate'
        /// </summary>
        [Fact]
        public void CurrencyExchangeRateTest()
        {
            // TODO unit test for the property 'CurrencyExchangeRate'
        }

        /// <summary>
        /// Test the property 'CustomMatchingReference'
        /// </summary>
        [Fact]
        public void CustomMatchingReferenceTest()
        {
            // TODO unit test for the property 'CustomMatchingReference'
        }

        /// <summary>
        /// Test the property 'CustomerAccountId'
        /// </summary>
        [Fact]
        public void CustomerAccountIdTest()
        {
            // TODO unit test for the property 'CustomerAccountId'
        }

        /// <summary>
        /// Test the property 'CustomerReference'
        /// </summary>
        [Fact]
        public void CustomerReferenceTest()
        {
            // TODO unit test for the property 'CustomerReference'
        }

        /// <summary>
        /// Test the property 'DeliveryAddress1'
        /// </summary>
        [Fact]
        public void DeliveryAddress1Test()
        {
            // TODO unit test for the property 'DeliveryAddress1'
        }

        /// <summary>
        /// Test the property 'DeliveryAddress2'
        /// </summary>
        [Fact]
        public void DeliveryAddress2Test()
        {
            // TODO unit test for the property 'DeliveryAddress2'
        }

        /// <summary>
        /// Test the property 'DeliveryAddressCity'
        /// </summary>
        [Fact]
        public void DeliveryAddressCityTest()
        {
            // TODO unit test for the property 'DeliveryAddressCity'
        }

        /// <summary>
        /// Test the property 'DeliveryAddressCountryCode'
        /// </summary>
        [Fact]
        public void DeliveryAddressCountryCodeTest()
        {
            // TODO unit test for the property 'DeliveryAddressCountryCode'
        }

        /// <summary>
        /// Test the property 'DeliveryAddressZipCode'
        /// </summary>
        [Fact]
        public void DeliveryAddressZipCodeTest()
        {
            // TODO unit test for the property 'DeliveryAddressZipCode'
        }

        /// <summary>
        /// Test the property 'DeliveryDate'
        /// </summary>
        [Fact]
        public void DeliveryDateTest()
        {
            // TODO unit test for the property 'DeliveryDate'
        }

        /// <summary>
        /// Test the property 'DeliveryTermId'
        /// </summary>
        [Fact]
        public void DeliveryTermIdTest()
        {
            // TODO unit test for the property 'DeliveryTermId'
        }

        /// <summary>
        /// Test the property 'DepartmentId'
        /// </summary>
        [Fact]
        public void DepartmentIdTest()
        {
            // TODO unit test for the property 'DepartmentId'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'Dim1Id'
        /// </summary>
        [Fact]
        public void Dim1IdTest()
        {
            // TODO unit test for the property 'Dim1Id'
        }

        /// <summary>
        /// Test the property 'Dim2Id'
        /// </summary>
        [Fact]
        public void Dim2IdTest()
        {
            // TODO unit test for the property 'Dim2Id'
        }

        /// <summary>
        /// Test the property 'Dim3Id'
        /// </summary>
        [Fact]
        public void Dim3IdTest()
        {
            // TODO unit test for the property 'Dim3Id'
        }

        /// <summary>
        /// Test the property 'DueDate'
        /// </summary>
        [Fact]
        public void DueDateTest()
        {
            // TODO unit test for the property 'DueDate'
        }

        /// <summary>
        /// Test the property 'ExternalImportReference'
        /// </summary>
        [Fact]
        public void ExternalImportReferenceTest()
        {
            // TODO unit test for the property 'ExternalImportReference'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'ImportedOrderNo'
        /// </summary>
        [Fact]
        public void ImportedOrderNoTest()
        {
            // TODO unit test for the property 'ImportedOrderNo'
        }

        /// <summary>
        /// Test the property 'ImportedVoucherNo'
        /// </summary>
        [Fact]
        public void ImportedVoucherNoTest()
        {
            // TODO unit test for the property 'ImportedVoucherNo'
        }

        /// <summary>
        /// Test the property 'InvoiceNo'
        /// </summary>
        [Fact]
        public void InvoiceNoTest()
        {
            // TODO unit test for the property 'InvoiceNo'
        }

        /// <summary>
        /// Test the property 'IsReversed'
        /// </summary>
        [Fact]
        public void IsReversedTest()
        {
            // TODO unit test for the property 'IsReversed'
        }

        /// <summary>
        /// Test the property 'LocationId'
        /// </summary>
        [Fact]
        public void LocationIdTest()
        {
            // TODO unit test for the property 'LocationId'
        }

        /// <summary>
        /// Test the property 'OutgoingInvoiceLines'
        /// </summary>
        [Fact]
        public void OutgoingInvoiceLinesTest()
        {
            // TODO unit test for the property 'OutgoingInvoiceLines'
        }

        /// <summary>
        /// Test the property 'ProjectId'
        /// </summary>
        [Fact]
        public void ProjectIdTest()
        {
            // TODO unit test for the property 'ProjectId'
        }

        /// <summary>
        /// Test the property 'PurchaseOrderReference'
        /// </summary>
        [Fact]
        public void PurchaseOrderReferenceTest()
        {
            // TODO unit test for the property 'PurchaseOrderReference'
        }

        /// <summary>
        /// Test the property 'SaftSourceId'
        /// </summary>
        [Fact]
        public void SaftSourceIdTest()
        {
            // TODO unit test for the property 'SaftSourceId'
        }

        /// <summary>
        /// Test the property 'SalesPersonEmployeeId'
        /// </summary>
        [Fact]
        public void SalesPersonEmployeeIdTest()
        {
            // TODO unit test for the property 'SalesPersonEmployeeId'
        }

        /// <summary>
        /// Test the property 'VoucherDate'
        /// </summary>
        [Fact]
        public void VoucherDateTest()
        {
            // TODO unit test for the property 'VoucherDate'
        }

        /// <summary>
        /// Test the property 'VoucherNo'
        /// </summary>
        [Fact]
        public void VoucherNoTest()
        {
            // TODO unit test for the property 'VoucherNo'
        }
    }
}
