/*
 * merged spec
 *
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PowerOfficeGoV2.Model;
using PowerOfficeGoV2.Client;
using System.Reflection;

namespace PowerOfficeGoV2.Test.Model
{
    /// <summary>
    ///  Class for testing ProductDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductDto
        //private ProductDto instance;

        public ProductDtoTests()
        {
            // TODO uncomment below to create an instance of ProductDto
            //instance = new ProductDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductDto
        /// </summary>
        [Fact]
        public void ProductDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductDto
            //Assert.IsType<ProductDto>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'CreatedDateTimeOffset'
        /// </summary>
        [Fact]
        public void CreatedDateTimeOffsetTest()
        {
            // TODO unit test for the property 'CreatedDateTimeOffset'
        }

        /// <summary>
        /// Test the property 'CreatedFromImportJournalId'
        /// </summary>
        [Fact]
        public void CreatedFromImportJournalIdTest()
        {
            // TODO unit test for the property 'CreatedFromImportJournalId'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'Gtin'
        /// </summary>
        [Fact]
        public void GtinTest()
        {
            // TODO unit test for the property 'Gtin'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'IsArchived'
        /// </summary>
        [Fact]
        public void IsArchivedTest()
        {
            // TODO unit test for the property 'IsArchived'
        }

        /// <summary>
        /// Test the property 'IsStockItem'
        /// </summary>
        [Fact]
        public void IsStockItemTest()
        {
            // TODO unit test for the property 'IsStockItem'
        }

        /// <summary>
        /// Test the property 'LastChangedDateTimeOffset'
        /// </summary>
        [Fact]
        public void LastChangedDateTimeOffsetTest()
        {
            // TODO unit test for the property 'LastChangedDateTimeOffset'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'OptionalSalesAccount'
        /// </summary>
        [Fact]
        public void OptionalSalesAccountTest()
        {
            // TODO unit test for the property 'OptionalSalesAccount'
        }

        /// <summary>
        /// Test the property 'OptionalSalesAccountAgricultureDepartment'
        /// </summary>
        [Fact]
        public void OptionalSalesAccountAgricultureDepartmentTest()
        {
            // TODO unit test for the property 'OptionalSalesAccountAgricultureDepartment'
        }

        /// <summary>
        /// Test the property 'OptionalSalesAccountId'
        /// </summary>
        [Fact]
        public void OptionalSalesAccountIdTest()
        {
            // TODO unit test for the property 'OptionalSalesAccountId'
        }

        /// <summary>
        /// Test the property 'ProductGroupCode'
        /// </summary>
        [Fact]
        public void ProductGroupCodeTest()
        {
            // TODO unit test for the property 'ProductGroupCode'
        }

        /// <summary>
        /// Test the property 'ProductGroupId'
        /// </summary>
        [Fact]
        public void ProductGroupIdTest()
        {
            // TODO unit test for the property 'ProductGroupId'
        }

        /// <summary>
        /// Test the property 'ProductType'
        /// </summary>
        [Fact]
        public void ProductTypeTest()
        {
            // TODO unit test for the property 'ProductType'
        }

        /// <summary>
        /// Test the property 'StandardSalesAccount'
        /// </summary>
        [Fact]
        public void StandardSalesAccountTest()
        {
            // TODO unit test for the property 'StandardSalesAccount'
        }

        /// <summary>
        /// Test the property 'StandardSalesAccountAgricultureDepartment'
        /// </summary>
        [Fact]
        public void StandardSalesAccountAgricultureDepartmentTest()
        {
            // TODO unit test for the property 'StandardSalesAccountAgricultureDepartment'
        }

        /// <summary>
        /// Test the property 'StandardSalesAccountId'
        /// </summary>
        [Fact]
        public void StandardSalesAccountIdTest()
        {
            // TODO unit test for the property 'StandardSalesAccountId'
        }

        /// <summary>
        /// Test the property 'StockAvailable'
        /// </summary>
        [Fact]
        public void StockAvailableTest()
        {
            // TODO unit test for the property 'StockAvailable'
        }

        /// <summary>
        /// Test the property 'StockOnHand'
        /// </summary>
        [Fact]
        public void StockOnHandTest()
        {
            // TODO unit test for the property 'StockOnHand'
        }

        /// <summary>
        /// Test the property 'StockOnHandLastChangedDatetimeOffset'
        /// </summary>
        [Fact]
        public void StockOnHandLastChangedDatetimeOffsetTest()
        {
            // TODO unit test for the property 'StockOnHandLastChangedDatetimeOffset'
        }

        /// <summary>
        /// Test the property 'UnitCost'
        /// </summary>
        [Fact]
        public void UnitCostTest()
        {
            // TODO unit test for the property 'UnitCost'
        }

        /// <summary>
        /// Test the property 'UnitOfMeasureCode'
        /// </summary>
        [Fact]
        public void UnitOfMeasureCodeTest()
        {
            // TODO unit test for the property 'UnitOfMeasureCode'
        }

        /// <summary>
        /// Test the property 'UnitPrice'
        /// </summary>
        [Fact]
        public void UnitPriceTest()
        {
            // TODO unit test for the property 'UnitPrice'
        }
    }
}
