/*
 * merged spec
 *
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PowerOfficeGoV2.Model;
using PowerOfficeGoV2.Client;
using System.Reflection;

namespace PowerOfficeGoV2.Test.Model
{
    /// <summary>
    ///  Class for testing SubLedgerNumberSeriesType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SubLedgerNumberSeriesTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SubLedgerNumberSeriesType
        //private SubLedgerNumberSeriesType instance;

        public SubLedgerNumberSeriesTypeTests()
        {
            // TODO uncomment below to create an instance of SubLedgerNumberSeriesType
            //instance = new SubLedgerNumberSeriesType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SubLedgerNumberSeriesType
        /// </summary>
        [Fact]
        public void SubLedgerNumberSeriesTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" SubLedgerNumberSeriesType
            //Assert.IsType<SubLedgerNumberSeriesType>(instance);
        }
    }
}
