/*
 * merged spec
 *
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PowerOfficeGoV2.Model;
using PowerOfficeGoV2.Client;
using System.Reflection;

namespace PowerOfficeGoV2.Test.Model
{
    /// <summary>
    ///  Class for testing VoucherApprovalStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VoucherApprovalStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VoucherApprovalStatus
        //private VoucherApprovalStatus instance;

        public VoucherApprovalStatusTests()
        {
            // TODO uncomment below to create an instance of VoucherApprovalStatus
            //instance = new VoucherApprovalStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VoucherApprovalStatus
        /// </summary>
        [Fact]
        public void VoucherApprovalStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" VoucherApprovalStatus
            //Assert.IsType<VoucherApprovalStatus>(instance);
        }
    }
}
