/*
 * merged spec
 *
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using PowerOfficeGoV2.Api;
using PowerOfficeGoV2.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace PowerOfficeGoV2.Test.Api
{
    /// <summary>
    ///  Class for testing DeliveryTermsApi
    /// </summary>
    public sealed class DeliveryTermsApiTests : ApiTestsBase
    {
        private readonly IDeliveryTermsApi _instance;

        public DeliveryTermsApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IDeliveryTermsApi>();
        }

        /// <summary>
        /// Test DeliveryTermsIdDelete
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task DeliveryTermsIdDeleteAsyncTest()
        {
            long id = default!;
            await _instance.DeliveryTermsIdDeleteAsync(id);
        }

        /// <summary>
        /// Test DeliveryTermsIdPatch
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task DeliveryTermsIdPatchAsyncTest()
        {
            long id = default!;
            Client.Option<List<Operation>> operation = default!;
            var response = await _instance.DeliveryTermsIdPatchAsync(id, operation);
            var model = response.Ok();
            Assert.IsType<DeliveryTermDto>(model);
        }

        /// <summary>
        /// Test DeliveryTermsPost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task DeliveryTermsPostAsyncTest()
        {
            Client.Option<DeliveryTermPostDto> deliveryTermPostDto = default!;
            var response = await _instance.DeliveryTermsPostAsync(deliveryTermPostDto);
            var model = response.Created();
            Assert.IsType<DeliveryTermDto>(model);
        }

        /// <summary>
        /// Test GetDeliveryTermById
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetDeliveryTermByIdAsyncTest()
        {
            long id = default!;
            var response = await _instance.GetDeliveryTermByIdAsync(id);
            var model = response.Ok();
            Assert.IsType<DeliveryTermDto>(model);
        }

        /// <summary>
        /// Test GetDeliveryTerms
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetDeliveryTermsAsyncTest()
        {
            Client.Option<ResourceParameters> resourceParameter = default!;
            var response = await _instance.GetDeliveryTermsAsync(resourceParameter);
            var model = response.Ok();
            Assert.IsType<List<DeliveryTermDto>>(model);
        }
    }
}
