/*
 * merged spec
 *
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using PowerOfficeGoV2.Api;
using PowerOfficeGoV2.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace PowerOfficeGoV2.Test.Api
{
    /// <summary>
    ///  Class for testing ManualJournalsApi
    /// </summary>
    public sealed class ManualJournalsApiTests : ApiTestsBase
    {
        private readonly IManualJournalsApi _instance;

        public ManualJournalsApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IManualJournalsApi>();
        }

        /// <summary>
        /// Test GetManualJournalById
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetManualJournalByIdAsyncTest()
        {
            Guid id = default!;
            var response = await _instance.GetManualJournalByIdAsync(id);
            var model = response.Ok();
            Assert.IsType<ManualJournalEntryVoucherDto>(model);
        }

        /// <summary>
        /// Test JournalEntryVouchersManualJournalsIdPatch
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task JournalEntryVouchersManualJournalsIdPatchAsyncTest()
        {
            Guid id = default!;
            Client.Option<List<Operation>> operation = default!;
            var response = await _instance.JournalEntryVouchersManualJournalsIdPatchAsync(id, operation);
            var model = response.Ok();
            Assert.IsType<ManualJournalEntryVoucherDto>(model);
        }

        /// <summary>
        /// Test JournalEntryVouchersManualJournalsIdVoucherLinesLineIdDelete
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task JournalEntryVouchersManualJournalsIdVoucherLinesLineIdDeleteAsyncTest()
        {
            Guid id = default!;
            long lineId = default!;
            await _instance.JournalEntryVouchersManualJournalsIdVoucherLinesLineIdDeleteAsync(id, lineId);
        }

        /// <summary>
        /// Test JournalEntryVouchersManualJournalsIdVoucherLinesLineIdPatch
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task JournalEntryVouchersManualJournalsIdVoucherLinesLineIdPatchAsyncTest()
        {
            Guid id = default!;
            long lineId = default!;
            Client.Option<List<Operation>> operation = default!;
            var response = await _instance.JournalEntryVouchersManualJournalsIdVoucherLinesLineIdPatchAsync(id, lineId, operation);
            var model = response.Ok();
            Assert.IsType<ManualJournalEntryVoucherLineDto>(model);
        }

        /// <summary>
        /// Test JournalEntryVouchersManualJournalsIdVoucherLinesPost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task JournalEntryVouchersManualJournalsIdVoucherLinesPostAsyncTest()
        {
            Guid id = default!;
            Client.Option<ManualJournalEntryVoucherLinePostDto> manualJournalEntryVoucherLinePostDto = default!;
            var response = await _instance.JournalEntryVouchersManualJournalsIdVoucherLinesPostAsync(id, manualJournalEntryVoucherLinePostDto);
            var model = response.Created();
            Assert.IsType<ManualJournalEntryVoucherDto>(model);
        }

        /// <summary>
        /// Test JournalEntryVouchersManualJournalsPost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task JournalEntryVouchersManualJournalsPostAsyncTest()
        {
            Client.Option<ManualJournalEntryVoucherPostDto> manualJournalEntryVoucherPostDto = default!;
            var response = await _instance.JournalEntryVouchersManualJournalsPostAsync(manualJournalEntryVoucherPostDto);
            var model = response.Created();
            Assert.IsType<ManualJournalEntryVoucherDto>(model);
        }
    }
}
