/*
 * merged spec
 *
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using PowerOfficeGoV2.Api;
using PowerOfficeGoV2.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace PowerOfficeGoV2.Test.Api
{
    /// <summary>
    ///  Class for testing VoucherDocumentationApi
    /// </summary>
    public sealed class VoucherDocumentationApiTests : ApiTestsBase
    {
        private readonly IVoucherDocumentationApi _instance;

        public VoucherDocumentationApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IVoucherDocumentationApi>();
        }

        /// <summary>
        /// Test AddVoucherDocumentation
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task AddVoucherDocumentationAsyncTest()
        {
            Guid id = default!;
            Client.Option<System.IO.Stream> file = default!;
            await _instance.AddVoucherDocumentationAsync(id, file);
        }

        /// <summary>
        /// Test GetVoucherDocumentation
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetVoucherDocumentationAsyncTest()
        {
            Guid id = default!;
            Client.Option<VoucherDocumentationType> documentationType = default!;
            await _instance.GetVoucherDocumentationAsync(id, documentationType);
        }

        /// <summary>
        /// Test VoucherDocumentationGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task VoucherDocumentationGetAsyncTest()
        {
            Client.Option<Guid> id = default!;
            Client.Option<long> voucherNo = default!;
            Client.Option<ResourceParameters> resourceParameter = default!;
            var response = await _instance.VoucherDocumentationGetAsync(id, voucherNo, resourceParameter);
            var model = response.Ok();
            Assert.IsType<List<VoucherDocumentationDto>>(model);
        }
    }
}
