name: Generate C# Client

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  workflow_dispatch:  # Allow manual triggering

jobs:
  generate-client:
    runs-on: ubuntu-latest

    steps:
        # Do we even need this step?
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'  # Use the latest .NET 9 SDK

      - name: Fetch API sepcs
        run: |
          mkdir specs
          cd specs
          wget https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/accountingsettings.json
          wget https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/accounttransactions.json
          wget https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/clientadmin.json
          wget https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/clientbankaccounts.json
          wget https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/clientIntegrationInformation.json
          wget https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/contactbankaccounts.json
          wget https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/contactdeliveryaddresses.json
          wget https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/contactgroups.json
          wget https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/contactpersons.json
          wget https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/customdimensions.json
          wget https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/customerledger.json
          wget https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/customers.json
          wget https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/departments.json
          wget https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/employees.json
          wget https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/enterprises.json
          wget https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/incomingInvoices.json
          wget https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/journalentryvouchers.json
          wget https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/locations.json
          wget https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/onboarding.json
          wget https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/organizationsettings.json
          wget https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/outgoingInvoices.json
          wget https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/payroll.json
          wget https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/products.json
          wget https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/projects.json
          wget https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/quality.json
          wget https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/salarylines.json
          wget https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/salesOrders.json
          wget https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/salessettings.json
          wget https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/supplierledger.json
          wget https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/suppliers.json
          wget https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/trialbalance.json
          wget https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/voucherapproval.json
          wget https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/voucherdocumentation.json
          wget https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/voucherposting.json

      - name: Generate C# Client using openapitools-generator-action
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: csharp
          command-args: --input-spec-root-directory specs

      - name: Build the generated client
        run: |
          cd ./csharp-client
          dotnet build

      - name: Pack the generated client into a NuGet package
        run: |
          cd ./csharp-client
          dotnet pack -c Release -o ./nupkg

      - name: Upload NuGet package as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: generated-nuget-package
          path: ./csharp-client/nupkg