name: Generate C# Client

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

jobs:
  generate-client:
    runs-on: ubuntu-latest

    steps:
        # Do we even need this step?
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate C# Client for AccountingSettings
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: csharp
          openapi-url: https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/accountingsettings.json

      - name: Generate C# Client for AccountintTransactions
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: csharp
          openapi-url: https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/accounttransactions.json

      - name: Generate C# Client for ClientAdmin
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: csharp
          openapi-url: https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/clientadmin.json

      - name: Generate C# Client for ClientBankAccounts
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: csharp
          openapi-url: https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/clientbankaccounts.json

      - name: Generate C# Client for ClientIntegrationInformation
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: csharp
          openapi-url: https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/clientIntegrationInformation.json

      - name: Generate C# Client for ContactBankAccounts
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: csharp
          openapi-url: https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/contactbankaccounts.json

      - name: Generate C# Client for ContactDeliveryAddresses
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: csharp
          openapi-url: https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/contactdeliveryaddresses.json

      - name: Generate C# Client for ContactGroups
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: csharp
          openapi-url: https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/contactgroups.json

      - name: Generate C# Client for ContactPersons
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: csharp
          openapi-url: https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/contactpersons.json

      - name: Generate C# Client for CustomDimensions
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: csharp
          openapi-url: https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/customdimensions.json

      - name: Generate C# Client for CustomerLedger
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: csharp
          openapi-url: https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/customerledger.json

      - name: Generate C# Client for Customers
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: csharp
          openapi-url: https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/customers.json

      - name: Generate C# Client for Departments
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: csharp
          openapi-url: https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/departments.json

      - name: Generate C# Client for Employees
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: csharp
          openapi-url: https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/employees.json

      - name: Generate C# Client for Enterprises
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: csharp
          openapi-url: https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/enterprises.json

      - name: Generate C# Client for IncomingInvoices
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: csharp
          openapi-url: https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/incomingInvoices.json

      - name: Generate C# Client for JournalentryVouchers
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: csharp
          openapi-url: https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/journalentryvouchers.json

      - name: Generate C# Client for Locations
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: csharp
          openapi-url: https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/locations.json

      - name: Generate C# Client for Onboarding
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: csharp
          openapi-url: https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/onboarding.json

      - name: Generate C# Client for OrganizationSettings
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: csharp
          openapi-url: https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/organizationsettings.json

      - name: Generate C# Client for OutgoingInvoices
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: csharp
          openapi-url: https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/outgoingInvoices.json

      - name: Generate C# Client for Payroll
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: csharp
          openapi-url: https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/payroll.json

      - name: Generate C# Client for Products
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: csharp
          openapi-url: https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/products.json

      - name: Generate C# Client for Projects
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: csharp
          openapi-url: https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/projects.json

      - name: Generate C# Client for Quality
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: csharp
          openapi-url: https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/quality.json

      - name: Generate C# Client for SalaryLines
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: csharp
          openapi-url: https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/salarylines.json

      - name: Generate C# Client for SalesOrders
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: csharp
          openapi-url: https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/salesOrders.json

      - name: Generate C# Client for SalesSettings
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: csharp
          openapi-url: https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/salessettings.json

      - name: Generate C# Client for SupplierLedger
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: csharp
          openapi-url: https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/supplierledger.json

      - name: Generate C# Client for Suppliers
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: csharp
          openapi-url: https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/suppliers.json

      - name: Generate C# Client for TrialBalance
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: csharp
          openapi-url: https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/trialbalance.json

      - name: Generate C# Client for VoucherApproval
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: csharp
          openapi-url: https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/voucherapproval.json

      - name: Generate C# Client for VoucherDocumentation
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: csharp
          openapi-url: https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/voucherdocumentation.json

      - name: Generate C# Client for VoucherPosting
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: csharp
          openapi-url: https://prdm0go0stor0apiv20eurw.z6.web.core.windows.net/openapispecs/voucherposting.json

      - name: Build the generated client
        run: |
          cd ./csharp-client
          dotnet build

      - name: Pack the generated client into a NuGet package
        run: |
          cd ./csharp-client
          dotnet pack -c Release -o ./nupkg

      - name: Upload NuGet package as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: generated-nuget-package
          path: ./csharp-client/nupkg